### ISSUE TITLE
FEATURE: 글 작성 페이지 구현

### ISSUE THREAD

**Issue by chaehyeon03** [jjwm10625/Roomfit#11]
# 📝 Description
사용자가 룸메이트/방을 구하는 게시글을 작성하는 화면

## 📌 Todo
- [ ] 사진 추가 필드 클릭 되게
- [ ] 폰트 크기 수정
- [ ] '위치 입력하기' api 연결 나중에

## 💡𝗥𝗲𝗳𝗲𝗿𝗲𝗻𝗰𝗲
WriteScreen.kt 에 들어가는 화면
