### ISSUE TITLE
FEATURE: 내 찜 목록 연결

### ISSUE THREAD

**Issue by chaehyeon03** [jjwm10625/Roomfit#45]
# 📝 Description
설명을 작성하세요

## 📌 Todo
- [x] 내 찜 목록 컴포넌트 수정
- [x] 홈 화면에서 찜하기 누르면 목록에 반영
- [x] 상세보기 누르면 detailscreen으로 연결
